function fields = pb_struct_sensehat
% STRUCT_SENSEHAT_FIELDS returns the struct fields for data returned from
% the rtimulsl.cc program running on a raspberry pi with a sense hat module

   fields = { ...
      'timestamp', ...
      'fusionPoseValid', ...
      'fusionPose_x', ...
      'fusionPose_y', ...
      'fusionPose_z', ...
      'fusionQPoseValid', ...
      'fusionQPose_scalar', ...
      'fusionQPose_x', ...
      'fusionQPose_y', ...
      'fusionQPose_z', ...
      'gyroValid', ...
      'gyro_x', ...
      'gyro_y', ...
      'gyro_z', ...
      'accelValid', ...
      'accel_x', ...
      'accel_y', ...
      'accel_z', ...
      'compassValid', ...
      'compass_x', ...
      'compass_y', ...
      'compass_z' ...
   };
end
